format_version: 10
pipelines:
  JMeter_DistTesting_make:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    environment_variables:
      ACRusername: jmeteracrrepo
      NumOfSlaves: 2
    secure_variables:
      ACRpwd: AES:93Shl6wGNWELgvubz8A56g==:nJYINiT7QDipJ5IFwPs/wIOzfOwnxSzgq8XGjeJSeq7E7guzR0qCCJJ0Pq+hAUxi
    materials:
      git-e912034:
        git: https://github.com/Rajasekar1990/gocd_DistTestCmp_make.git
        username: Rajasekar1990
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:6H8j1ldfMqlLY+zxGdNigQ==:SzWrCDRamRRv49Cv8D8GHA==
        destination: gocd_DistTestCmp_make
    stages:
    - ACR_Login:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          Login_To_ACR:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Login to ACR
                command: echo
                run_if: passed
            - exec:
                arguments:
                - ACR_Login
                command: make
                run_if: passed
    - ACR_JmMaster_Build_Push_Image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          JMeter_Master_Build_Img:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ACR_Build_Master_Img
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed                
          JMeter_Master_Push_Img:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ACR_Push_Master_Img
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed        
    - ACR_JmSlave_Build_Push_Image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          JMeter_Slave_Build_Img:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ACR_Build_Slave_Img
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed
          JMeter_Slave_Push_Img:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - ACR_Push_Slave_Img
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed
    - Execute_Performance_Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Run_Load_Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Run_Load_Test
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed
    - ReportCreation:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          CreateHTMLReport:
            timeout: 0
            artifacts:
            - build:
                source: Report*
                destination: ''
            tasks:
            - exec:
                arguments:
                - Create_HTML_Report
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed
    - CleanUpTestEnvironment:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
           KillandRemoveContainers:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - CleanUp_Workspace
                command: make
                working_directory: gocd_DistTestCmp_make
                run_if: passed